autocmd FileType php call foldfunctions#php()
autocmd FileType javascript call foldfunctions#javascript()
autocmd FileType ruby call foldfunctions#ruby()
autocmd FileType vim call foldfunctions#vim()
autocmd FileType cpp call foldfunctions#cpp()
